# Generated by Django 5.0.2 on 2024-02-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleadmodule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='Task_Priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
    ]
