# Generated by Django 4.1 on 2024-03-05 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminmodule", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
