# Generated by Django 4.1 on 2024-03-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adminmodule", "0002_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=30, unique=True)),
                ("address", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "register_table",
            },
        ),
    ]
