# Generated by Django 4.1 on 2024-03-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("adminmodule", "0004_alter_register_managers_register_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="groups",
            field=models.ManyToManyField(
                related_name="register_related_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="register_related_user_permissions", to="auth.permission"
            ),
        ),
    ]
