# Generated by Django 4.1 on 2024-03-08 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminmodule", "0005_alter_register_groups_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Register",
        ),
    ]
