# Generated by Django 5.0.2 on 2024-02-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammatesmodule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDetails',
        ),
    ]
