# Generated by Django 5.0.2 on 2024-02-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammatesmodule', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='End_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='Start_Date',
            field=models.DateField(),
        ),
    ]
