# Generated by Django 5.0.2 on 2024-02-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammatesmodule', '0004_alter_taskdetails_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDetails',
        ),
    ]
