# Generated by Django 5.0.2 on 2024-02-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teammatesmodule', '0005_delete_taskdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Title', models.CharField(max_length=255)),
                ('Task_Priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
