# Generated by Django 5.0.2 on 2024-02-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammatesmodule', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskDetails',
            new_name='PersonalTaskDetails',
        ),
    ]
